// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Recruit.Models;
using System;

namespace RecruitWeb.Migrations
{
    [DbContext(typeof(RecruitDbContext))]
    [Migration("20180227004842_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Recruit.Models.recruit_user", b =>
                {
                    b.Property<string>("uuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyAddress");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyContact");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("addtime");

                    b.Property<string>("cardno")
                        .HasMaxLength(14);

                    b.Property<string>("email");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("phone");

                    b.Property<string>("pwd")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("role");

                    b.Property<string>("uname")
                        .HasMaxLength(20);

                    b.HasKey("uuid");

                    b.ToTable("recruit_user");
                });
#pragma warning restore 612, 618
        }
    }
}
